spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: nuraimed-back
  datasource:
    url: jdbc:postgresql://${POSTGRES_ADDRESS}:${POSTGRES_ADDRESS_PORT}/${POSTGRES_DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: db/changelog/changelog-master.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET_KEY}
server:
  port: 8080